# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile

play.filters.headers {
  contentSecurityPolicy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.jquery.com; connect-src 'self' ws:"
}


twitter {
  apiKey =       "EnYRL5SlG0nTLAHjjof5X1PHj";
  apiSecret =    "6DpYTHRAayrHq0YQ5Ug1voCEB2M4ZuI0EBZ7aXUTnu3WbDNnU4";
  token =        "976176080850751489-gepbYt1TFQQGd1Jdd3kpZU9N0cOFS4f";
  tokenSecret =  "rwlr0OZXSsloYFdN7WR9vpTOWJfdRIii4Bkhr9SuoRmcd";
}